### ISSUE TITLE
after update wallet app does not work

### ISSUE THREAD

**Issue by vabals** [horizontalsystems/unstoppable-wallet-android#4428] opened 2021-12-10 09:49 UTC
after update to Version 0.23.0 wallet does not start. only the very first starting screen is visible.

fdroid repo
pixel 3
graphene os, build: SP1A.210812.015.2021120717

**Comment by rafaelekol** [comment] 2021-12-10 10:57
Can you send screenshot of the screen you see.
I tried to reproduce, but couldn't see your issue. After update you normally should see screen with changelogs. By pressing close button at top right you should see wallet.

**Comment by vabals** [comment] 2021-12-10 11:09
![signal-2021-12-10-130434_001](https://user-images.githubusercontent.com/81348255/145564349-d41156bc-0e32-44d9-88f8-92e739261ea2.png)
this screen pops up for a half second and app terminates. cache clearing, force stoppind did not help.

i tried to reproduce with xperia xz2, fdroid app, lineage os. everything works ok.

**Comment by rafaelekol** [comment] 2021-12-10 11:11
What Android version do you have on pixel 3?

**Comment by vabals** [comment] 2021-12-10 11:14
android 12
https://github.com/GrapheneOS/platform_manifest/releases/tag/SP1A.210812.015.2021120717

**Comment by hoanghiephui** [comment] 2021-12-11 02:06
> android 12 https://github.com/GrapheneOS/platform_manifest/releases/tag/SP1A.210812.015.2021120717
> 
> EDIT: i did some more testing with 2 more phones and was able to reproduce this problem, which occurs only on pixel 3 with grapheneos SP1A.210812.015.2021120717, app 0.23.0. after clearing storage & cache app starts fine, but crashes the moment you enable tor in privacy menu.

I thinks, it crashed due to Room db. @rafaelekol

**Comment by rafaelekol** [comment] 2021-12-11 05:00
Enabling Tor seems to be crashing app on Android 12. I will work on fix for this case on Monday.
@vabals did you have Tor enabled on your app? Also what kind of coins did you have enabled? I need to reproduce your crash.

**Comment by vabals** [comment] 2021-12-11 14:39
@rafaelekol yes, app crashes the moment you enable tor inside the app. i just generated android bug report, can upload some information if this could help.

**Comment by rafaelekol** [comment] 2021-12-11 15:38
@vabals If you had Tor enabled before updating app. Then the cause of crash is Tor. Otherwise it can be some issue with database migration.

**Closed** 2021-12-13 11:42 UTC
