### ISSUE TITLE
java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#6265] opened 2023-06-30 06:37 UTC
Exception java.net.SocketTimeoutException: timeout
  at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException (Http2Stream.kt:704)
  at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut (Http2Stream.kt:713)
  at okhttp3.internal.http2.Http2Stream.takeHeaders (Http2Stream.kt:150)
  at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders (Http2ExchangeCodec.kt:97)
  at okhttp3.internal.connection.Exchange.readResponseHeaders (Exchange.kt:111)
  at okhttp3.internal.http.CallServerInterceptor.intercept (CallServerInterceptor.kt:93)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.kt:34)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.kt:95)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt:84)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:65)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at io.horizontalsystems.tronkit.network.TronGridService._init_$lambda$2 (TronGridService.kt:49)
  at io.horizontalsystems.tronkit.network.TronGridService.$r8$lambda$sF9k4zUIrb_sJx0rE4O4hduytS8
  at io.horizontalsystems.tronkit.network.TronGridService$$ExternalSyntheticLambda1.intercept
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at okhttp3.logging.HttpLoggingInterceptor.intercept (HttpLoggingInterceptor.kt:233)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:205)
  at okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:533)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)

**Comment by rafaelekol** [comment] 2023-06-30 09:54
duplicate of #6266

**Closed by rafaelekol** 2023-06-30 09:54 UTC
Labels: hotfix
