### ISSUE TITLE
Incorrect balance of receiving USDT (TRC20)

### ISSUE THREAD

**Issue by TheFuzzStone** [horizontalsystems/unstoppable-wallet-android#6827] opened 2023-11-14 09:27 UTC
I received 1000 USDT (TRC20). But the wallet showed 2000 USDT (TRC20) on the "Transactions" tab. Yes, I double-checked in Tronscan and there is 1000 USDT.

While the total balance of the wallet is correct and the 1000 I received was counted as 1000.
I cleared the cache but nothing changed, the "Transactions" tab keeps showing 2000.

This is a dangerous bug for those who use the wallet for work. Now I can't trust the "Transactions" tab and will check in Tronscan every time (which is inconvenient).

Version: 0.36.0 (from F-Droid)

**Comment by TheFuzzStone** [comment] 2023-11-14 15:21
Also, this invalid amount transaction shows up weird if you open it. It's like split on two parts:

![IMG_20231114_161003_820](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/16173361/21559e90-512d-4eb9-8f36-52b2cdc4a48b)

**Comment by omurovch** [comment] 2023-11-15 04:30
Thanks for reporting! Will look into it asap.

**Comment by omurovch** [comment] 2023-11-17 05:32
> Also, this invalid amount transaction shows up weird if you open it. It's like split on two parts:
> 
> ![IMG_20231114_161003_820](https://user-images.githubusercontent.com/16173361/282826772-21559e90-512d-4eb9-8f36-52b2cdc4a48b.jpg)

what kind of transaction is it? is it simple Trc20 transfer or other type of contract call?

**Comment by TheFuzzStone** [comment] 2023-11-17 09:55
> what kind of transaction is it? is it simple Trc20 transfer or other type of contract call?

A friend just sent me USDT (TRC20).

> in transactions list how amount is displayed, as 1000 or 2000? (if possible please attach screenshot)

Emm... you just quoted the screenshot. You you see it? It's displayed as 2 transactions per 1000.

**Comment by omurovch** [comment] 2023-11-17 12:18
Very strange. Couldn't reproduce it. Can you import the wallet again and see if the problem remains?

**Comment by TheFuzzStone** [comment] 2023-11-18 05:30
> Couldn't reproduce it.

It only happened once. Since you fixed the Tron synchronization issue, I've been using UW as my primary wallet for USDT (TRC20) for work, and some of my colleagues have switched from other wallets too. I asked them if they had a similar problem, they said no.

I suggest to leave this issue open for now. If during 1 month I will not have a similar problem (or other users), I will report here.

**Comment by omurovch** [comment] 2023-11-20 03:20
> > Couldn't reproduce it.
> 
> It only happened once. Since you fixed the Tron synchronization issue, I've been using UW as my primary wallet for USDT (TRC20) for work, and some of my colleagues have switched from other wallets too. I asked them if they had a similar problem, they said no.
> 
> I suggest to leave this issue open for now. If during 1 month I will not have a similar problem (or other users), I will report here.

Ok, great! So just to clarify, did reimporting the wallet solve the problem? It is important for understanding the cause of the problem.

**Comment by TheFuzzStone** [comment] 2023-11-20 18:31
> did reimporting the wallet solve the problem?

I'll tell you tomorrow. I'm away from my backups today. :)

Tomorrow I will delete the wallet data (cache + data), it will be like a clean installation, and then I will restore the wallet.

**Comment by omurovch** [comment] 2023-11-27 08:16
Closing the issue for now. Please feel free to reopen it if problem occurs again.

**Closed by omurovch** 2023-11-27 08:16 UTC
Labels: bug
