### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by coderzstas** [horizontalsystems/unstoppable-wallet-android#1256] opened 2019-08-29 13:53 UTC
When trying to copy wallet adress - app crashes .

**Comment by rafaelekol** [comment] 2019-08-30 03:32
Can you provide more details about crash. On which screen, which coin this is happening?

**Comment by coderzstas** [comment] 2019-08-30 15:17
sure , on balance page when clicking on Ethereum > Receive > and click on "Your Adress" .

here is crash log

> 08-30 11:23:27.081 E/AndroidRuntime(6029): FATAL EXCEPTION: main
08-30 11:23:27.081 E/AndroidRuntime(6029): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(int, android.graphics.PorterDuff$Mode)' on a null object reference
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at io.horizontalsystems.bankwallet.viewHelpers.HudHelper.showHudNotification(HudHelper.kt:36)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at io.horizontalsystems.bankwallet.viewHelpers.HudHelper.showSuccessMessage(HudHelper.kt:18)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at io.horizontalsystems.bankwallet.modules.receive.ReceiveView$showCopiedObserver$1.onChanged(ReceiveView.kt:61)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at io.horizontalsystems.bankwallet.modules.receive.ReceiveView$showCopiedObserver$1.onChanged(ReceiveView.kt:15)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at io.horizontalsystems.bankwallet.SingleLiveEvent$observe$1.onChanged(SingleLiveEvent.kt:20)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at io.horizontalsystems.bankwallet.SingleLiveEvent.setValue(SingleLiveEvent.kt:14)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at io.horizontalsystems.bankwallet.SingleLiveEvent.call(SingleLiveEvent.kt:31)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at io.horizontalsystems.bankwallet.modules.receive.ReceiveViewModel.showCopied(ReceiveViewModel.kt:33)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at io.horizontalsystems.bankwallet.modules.receive.ReceivePresenter.didCopyToClipboard(ReceivePresenter.kt:44)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at io.horizontalsystems.bankwallet.modules.receive.ReceiveInteractor.copyToClipboard(ReceiveInteractor.kt:24)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at io.horizontalsystems.bankwallet.modules.receive.ReceivePresenter.onAddressClick(ReceivePresenter.kt:40)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at io.horizontalsystems.bankwallet.modules.receive.ReceiveView$bind$3.onClick(ReceiveView.kt:41)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at android.view.View.performClick(View.java:6599)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at android.view.View.performClickInternal(View.java:6576)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at android.view.View.access$3100(View.java:780)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at android.view.View$PerformClick.run(View.java:25931)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at android.os.Handler.handleCallback(Handler.java:873)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at android.os.Looper.loop(Looper.java:193)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at android.app.ActivityThread.main(ActivityThread.java:6671)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at java.lang.reflect.Method.invoke(Native Method)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
08-30 11:23:27.081 E/AndroidRuntime(6029): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
08-30 11:23:27.105 E/InputDispatcher(906): channel 'b234772 io.horizontalsystems.bankwallet.modules.main.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

>

**Comment by rafaelekol** [comment] 2019-09-03 04:17
I tried to reproduce this crash, but couldn't. Can you also tell what the version of Android, and is device is real device or emulator?

**Comment by coderzstas** [comment] 2019-09-03 07:37
Android 9 , lineage os , oneplus 6t

**Comment by rafaelekol** [comment] 2019-09-03 08:11
Can you also try clicking on address lines in Transactions screen, to make sure that is also crashing while trying to show Toast with message.
http://imgsafe.org/image/93f48426b3

**Comment by coderzstas** [comment] 2019-09-03 08:32
yep there crashing too

**Comment by rafaelekol** [comment] 2019-09-03 08:59
Logs points to NullPointerException in class `HudHelper` line 36.
We can't reproduce this crash. Can you try to debug this, and tell us which object exactly is `null` on your phone.

**Comment by coderzstas** [comment] 2019-09-03 09:28
ok , intresting i commented this line         // toast.view.background.setColorFilter(ContextCompat.getColor(toast.view.context, backgroundColor), PorterDuff.Mode.SRC_IN) and crash was fixed for me

**Comment by rafaelekol** [comment] 2019-09-03 09:34
This line is coloring standard Toast background with new color. It seems that `toast.view.background` is null in your case. 
I will close this ticket, since we can't reproduce it here.

**Closed by rafaelekol** 2019-09-03 09:34 UTC
