### ISSUE TITLE
Wallet shows wrong Bitcoin balance

### ISSUE THREAD

**Issue by nandlab** [horizontalsystems/unstoppable-wallet-android#6510] opened 2023-08-28 12:46 UTC
Does the Unstoppable Wallet on Android support P2WPKH addresses?

I did a Bitcoin transaction and received change on a P2WPKH address, but Unstoppable Wallet now incorrectly shows a balance of zero. I have BIP44, BIP49, BIP84 and BIP86 enabled. When I open the same wallet in Electrum the remaining balance is shown correctly.
I am using a HD wallet with 12 words and a passphrase as a seed.

**Comment by omurovch** [comment] 2023-08-30 07:09
Hi @nandlab,

Thanks for heads up! Can you try to restore the wallet again and see if it helps?

**Comment by nandlab** [comment] 2023-08-31 21:24
Hi @omurovch,
after restoring the wallet the correct balance appeared in BIP84 :)
I still think it was a software bug that should be investigated.

**Comment by omurovch** [comment] 2023-09-01 05:29
Yes, it should be in BIP84 since it is P2WPKH. Very strange, we couldn't reproduce it. Anyway closing the issue for now,
please feel free to reopen if it happens again.

**Closed by omurovch** 2023-09-01 05:29 UTC
