### ISSUE TITLE
I cannot disabling VPN every time I need to sync BCH and DASH chains

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#6158] opened 2023-06-03 15:20 UTC
The problem persists only with these two blockchains. All the others work correctly.

I can’t expose my device to the network without a VPN, also because this trick isn’t always work.

A definitive solution must be found. If it doesn't a UW issue then write to the coin development teams. I don’t more know what to do anymore.

**Comment by abdrasulov** [comment] 2023-09-07 07:00
Hi folks,

Since we could not reproduce this issue, we are closing it for now. Let us know if you face this issue again. We'll reopen it then.

**Closed by abdrasulov** 2023-09-07 07:00 UTC
