### ISSUE TITLE
Unable to send coin, all transactions stuck pending

### ISSUE THREAD

**Issue by Taklun86** [horizontalsystems/unstoppable-wallet-android#989] opened 2019-06-24 10:45 UTC
Tried to send coin on Fri but I messed up my fees by accident so I thought they just weren't picked up and would eventually drop off. Still waiting but I just tried to send coin from my wallet with max fees but it's still not registering anything on the blockchain.

Starting to look like my wallet just is not connected to any network at all? The send button keeps grey'ing out every do often. Currently I'm stuck in limbo with 4 transactions apparently pending but if I try to verify them, all servers appear offline. 

If this is not connecting then can I do something to cancel my pending transactions so I can release my coins as it appears they were never actually broadcast?

**Comment by Taklun86** [comment] 2019-06-25 02:15
Resolved by restoring wallet via slow method but even after restoration, send button is blacked out most of the time. The btc logo is permanently a solid circle, only time it is not is if i remove btc and add it back to my wallet but it quickly goes back to being greyed out.

**Comment by rafaelekol** [comment] 2019-06-25 04:50
We are aware of these bugs. Currently we are working on them. We will push fixes shortly.

**Comment by horsys** [comment] 2019-06-25 05:40
> Resolved by restoring wallet via slow method but even after restoration, send button is blacked out most of the time. The btc logo is permanently a solid circle, only time it is not is if i remove btc and add it back to my wallet but it quickly goes back to being greyed out.

Hi Taklun, 

Thanks for the feedback. 

- in regards to you issue with stuck transaction and inactive send button. We had a team meeting about this today and it looks like your wallet always tries to sync itself with the blockchain and not able to do so in a reasonable amount of time or at all. As a result you get inactive send button most of the time. We decided to change synchronization logic which should address the issues we believe might be causing the wallet to act like that on a slow internet connection. That would address the issue with solid circle (spinner) on BTC logo.

- are you on mobile network or wifi? If it's mobile, is it 3G/4G network or a slower one?

**Comment by Taklun86** [comment] 2019-06-25 09:05
Thanks for response! Much appreciatec.

Currently I am on wifi network at home but still having the problem but while i was in work earlier the same problem persisted on their wifi and only time my wallet seemed to function properly was when on 4g. When connected to 3g the problem still remained.

Problem with the wifi may be that my device can only use 2.4Ghz and not 5Ghz.

In the meantime I'll try the wallet on other devices just to see if i run into any problems.

**Comment by Taklun86** [comment] 2019-06-25 11:07
Everything seemed to be fine while using 4G until I tried to send coin. Got the sent message but currently the transaction is still pending with no confirmations after 90mins and I maxed out the transaction fee.

I look to be in the same situation as before.

**Comment by Taklun86** [comment] 2019-06-25 17:45
I've just reset my wallet. Won't do anything till next update is released.

**Comment by abdrasulov** [comment] 2019-06-26 04:46
Hi Taklun,

We've started working on this issue. The details you've provided helped us to reproduce it. We're planning to release the fix in the upcoming release.

**Comment by esengulov** [comment] 2019-06-26 05:46
> I've just reset my wallet. Won't do anything till next update is released.

The update with the fix likely to come by the end of this week. This is on priority list at the moment

**Comment by Taklun86** [comment] 2019-06-27 13:01
Thats truly awesome! Thanks so much for all your hard work! Have a blessed week!

**Comment by Dianaaiym** [comment] 2019-07-05 05:15
> Thats truly awesome! Thanks so much for all your hard work! Have a blessed week!

Hello! Thank you very much for your feedback. I'm glad to report that all fixed now! New version 0.6.3  available https://play.google.com/store/apps/details?id=io.horizontalsystems.bankwallet
Enjoy!

**Closed by Dianaaiym** 2019-07-05 05:15 UTC
