### ISSUE TITLE
feature request: restore ETH wallet by import keystore

### ISSUE THREAD

**Issue by ivysrono** [horizontalsystems/unstoppable-wallet-android#2025] opened 2020-03-29 08:41 UTC

**Comment by esengulov** [comment] 2020-03-30 06:25
hi @ivysrono we'll look into it soon, most probably we will add it in the near future. Thanks for heads up. Meanwhile, add 'postponed' label to the ticket

**Comment by esengulov** [comment] 2020-11-02 09:14
Duplicate of https://github.com/horizontalsystems/unstoppable-wallet-android/issues/2542

**Closed by esengulov** 2020-11-02 09:14 UTC
Labels: postponed
