### ISSUE TITLE
Update the balance card design

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-android#5516] opened 2022-11-16 06:58 UTC
Update all margins and paddings 

layouts:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=63074%3A399014&t=9ZHUKsSviPOsYUOP-4

**Comment by rafaelekol** [comment] 2022-12-16 09:50
Duplicate of #5514

**Closed by rafaelekol** 2022-12-16 09:50 UTC
