### ISSUE TITLE
EVM private key incorrect length?

### ISSUE THREAD

**Issue by fungs** [horizontalsystems/unstoppable-wallet-android#5536] opened 2022-11-22 22:12 UTC
I created an ethereum account and address in the Android app. I wanted to import the same account into myCrypto for verification. However, when using the EVM private key, it shows me a 62 characters string whereas myCrypto states that the private key must be 64 characters. Is the private key complete?

Reference: https://support.mycrypto.com/general-knowledge/ethereum-blockchain/difference-between-wallet-types

I also failed to import via mnemonic phrase + password. I assume that both apps are using different derivation paths?

**Comment by omurovch** [comment] 2022-11-23 06:24
Hi @fungs 

Right, evm private key should be 64 hex characters (32 bytes). It is very strange that it shows 62 chars. Can you create another wallet (just for testing) and see if it also shows 62 char evm private key?

**Comment by fungs** [comment] 2022-11-23 07:58
I forgot to mention: app version is 0.28.0 and I used an 18 word phrase + password for creation. Will do some tests and report here.

**Comment by fungs** [comment] 2022-11-24 15:32
I created 3 more wallets including the same settings but different password, which all had 64 character keys. So I will test a little more. But for some reason, the first wallet I created has a bad key and I can still see and use it.

**Comment by omurovch** [comment] 2022-11-25 05:04
Creating again the first wallet using the same mnemonic + password gives the same 62 character key?

**Comment by esengulov** [comment] 2023-01-02 07:55
@fungs any updates on this?

**Comment by fungs** [comment] 2023-01-15 19:51
To be honest, I didn't see any option to set the mnemonic myself. So I have no new insights. The other wallets I created had a correct key.

**Comment by esengulov** [comment] 2023-01-16 08:15
> To be honest, I didn't see any option to set the mnemonic myself. So I have no new insights. The other wallets I created had a correct key.

You may try to  restore the wallet using the same mnemonic +pass

**Comment by esengulov** [comment] 2023-04-04 08:52
@fungs closing the issue for the time being as we are not able to reproduce it

**Closed by esengulov** 2023-04-04 08:52 UTC
