### ISSUE TITLE
SPL tokens on Solana network don't work at all

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7074] opened 2024-02-14 14:54 UTC
Is it the same issue of #7031 or a different one?

![1000106092](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/42705555-775f-4adc-9164-47e3a472fe3f)

**Comment by notpri** [comment] 2024-02-14 16:12
hey its fixed. that is a sync issue that is caused by slow connection or something but it gets fixed instantly. and i just checked it works fine. so please be patient when you create an issue like this again. they gets fixed in seconds and minutes

**Comment by Dianaaiym** [comment] 2024-02-15 06:19
> Is it the same issue of #7031 or a different one?

Hi,

Yes, it's the same problem https://github.com/horizontalsystems/unstoppable-wallet-android/issues/7031

**Closed by Dianaaiym** 2024-02-15 06:19 UTC
