### ISSUE TITLE
Issue arising when switching between wallets

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-android#7380] opened 2024-04-30 06:25 UTC
- Restore the wallet with the TON enabled;
- Launch the wallet with TON;
- Switch between wallets;
- Notice that data from the previous wallet is retained upon switching.

https://github.com/horizontalsystems/unstoppable-wallet-android/assets/22589457/9ca22354-5051-4487-9692-fc50c4693df2

**Comment by abdrasulov** [comment] 2024-06-06 12:16
We could not reproduce it. Closing for now

**Closed by abdrasulov** 2024-06-06 12:16 UTC
Labels: bug
