### ISSUE TITLE
BCH sync issues (not always)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-android#7375] opened 2024-04-28 10:07 UTC
![1000109575](https://github.com/horizontalsystems/unstoppable-wallet-android/assets/113377431/c674296c-415c-415c-91f3-95ee404ba14d)

**Comment by johncenaaaaaaa** [comment] 2024-04-29 18:22
I can vouch for that. I have experienced exactly the same thing this week.

**Comment by omurovch** [comment] 2024-04-30 06:49
> Currently working properly. Do you investigate or I close?

Which BTC-like blockchains were enabled when you experienced issues with BCH?

**Comment by omurovch** [comment] 2024-05-01 09:45
Could not reproduce it. Seems it was related to network. Either internet was slow or could not find blockchain peers. Closing it for now. Please feel free to reopen in case it happens again.

**Closed by omurovch** 2024-05-01 09:45 UTC
